### ISSUE TITLE
Test CDT tasks as npm scripts

### ISSUE THREAD

**Issue by edwingamboa** [cubbles/cubbles-coder-devtools#11]
Check that the CDT tasks can be run as npm scripts in shell.

The tasks that needed to be modified are presented below. For each package a new version was released.
- [x] cubbles/cubx-prepare-webpackage-release#1 ([1.3.0](https://www.npmjs.com/package/cubx-prepare-webpackage-release/v/1.3.0) version was released)
- [x] cubbles/cubx-set-webpackage-version#1 ([1.1.0](https://www.npmjs.com/package/cubx-set-webpackage-version/v/1.1.0) version was released)
- [x] cubbles/cubx-generate-webpackage-readme-file#1 ([1.1.0](https://www.npmjs.com/package/cubx-generate-webpackage-readme-file/v/1.1.0) version was released)
- [x] cubbles/cubx-rename-artifact#4 ([1.3.0](https://www.npmjs.com/package/cubx-rename-artifact/v/1.3.0) version was released)
- [x] cubbles/cubx-webpackage-rte-update#1 ([1.2.0](https://www.npmjs.com/package/cubx-webpackage-rte-update/v/1.2.0) version was released)
