### ISSUE TITLE
PoC: use webpack to build a webpackage

### ISSUE THREAD

**Issue by hrbu** [cubbles/cubbles-coder-devtools#2]
Currently a developer uploads the source files of a webpackage. There is NO step before to compile/transform/optimize anything. The recent tests show the benefits of frameworks/languages like react, typescript etc. Most of those approaches require the source files to be compiled/transformed into executable assets.

So this seem to be the right time to provide a *"build step"*, that 
1. provides a useful default configuration and 
2. allows to be extended by developers. 

Webpack (https://webpack.js.org/) is a framework that seems to match the requirements.

# Acceptance Criterias
- [x] `init`: Developers are able to initialize a project via cli.
- [x] `elementary`: Developers are able to initialize an elementary via cli.
- [x] docs: The new/extended directory structure is described.

# Task(s)
Run a PoC to test _webpack_ is useful to support the idea.
- [x] The PoC sources are available public: https://github.com/hrbu/hrbu-webpack-poc
- [x] Create sub generator `init` to init a webpackage within a npm package (incl. a default `webpack.config.js`)
- [ ] Create sub generator `createElementary` to init a elementary component (incl. a default `webpack.config.js`)
- [ ] Create sub generator `createCompound` to init a elementary component (incl. a default `webpack.config.js`)
- [ ] ...

# Resources
- Webpack (https://webpack.js.org/) is such kind of framework.
- https://css-tricks.com/css-modules-part-2-getting-started/ describes, how to use webpack to use css modules (_"CSS modules are CSS files in which all class names and animation names are scoped locally by default."_ [https://css-tricks.com/css-modules-part-1-need/#article-header-id-1])

**Comment by hrbu** [comment]
```
$ npx webpack --context ../webpackages/hrbu-webpack-poc/ --config ../webpackages/hrbu-webpack-poc/webpack.config.js
```

This runs `webpack` from the `cubbles-coder-devtools` folder on the webpackage `hrbu-webpack-poc` using the `webpack.config.js` inside this folder.

> Note: The npx command which ships with Node 8.2 or higher, runs the webpack binary (./node_modules/.bin/webpack). // [webpack > Getting started](https://webpack.js.org/guides/getting-started/#creating-a-bundle)

**Comment by hrbu** [comment]
The PoC is seen as "done". Next steps will be managed in the context of cubbles/cubbles#20
"Extend Coder Template"
