### ISSUE TITLE
As developer I will be able to update the used RTE version in the active webpackage.

### ISSUE THREAD

**Issue by pwrinc** [cubbles/cubbles-coder-devtools#6]
Please create a task which updates the version of `cubx.core.rte` for every usage in given webpackage.

**Acceptance criteria:**
- [x] a task `_webpackage-updateRte` is available
- [x] a target version can be provided by cli input (e.g. `3.0.4`)
- [x] check given input against pattern `[major].[minor].[patch]` (use regexp from webpackage document api)
- [x] every usage of `cubx.core.rte` is updated to use provided version 
- [x] an npm module cubx-webpackage-rte-update is published
- [x] an grunt package cubx-grunt-webpackage-rte-update is published 
- [] When target version is 3.x appropriate changes should be performed in html pages
